name: 手动构建

on:
  workflow_dispatch:
    inputs:
      platform:
        description: '选择构建的平台'
        required: false
        type: choice
        options:
          - all
          - android
          - windows
          - linux
          - macos

jobs:
  构建:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
            arch: amd64
          - platform: linux
            os: ubuntu-latest
            arch: amd64
          - platform: macos
            os: macos-13
            arch: amd64
          - platform: macos
            os: macos-latest
            arch: arm64

    if: inputs.platform == 'all' || inputs.platform == matrix.platform

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 创建 dist 目录
        run: mkdir -p dist

      - name: 配置 JAVA (Android)
        if: startsWith(matrix.platform, 'android')
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: 配置 NDK (Android)
        if: startsWith(matrix.platform, 'android')
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          add-to-path: true
          link-to-sdk: true

      - name: 配置 Android 签名
        if: startsWith(matrix.platform, 'android')
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/keystore.jks
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/local.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/local.properties

      - name: 配置 Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: 配置 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5
          channel: stable
          cache: true

      - name: 获取 Flutter 依赖
        run: flutter pub get

      - name: 设置构建环境
        run: dart setup.dart ${{ matrix.platform }} ${{ matrix.arch && format('--arch {0}', matrix.arch) }}

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.platform }}${{ matrix.arch && format('-{0}', matrix.arch) }}
          path: dist/
          overwrite: true

  上传:
    needs: [ 构建 ]
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 创建 dist 目录
        run: mkdir -p dist

      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          path: dist/
          pattern: artifact-*
          merge-multiple: true

      - name: 上传最终构建产物
        uses: actions/upload-artifact@v4
        with:
          name: final-build-output
          path: dist/
          overwrite: true
